import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

/**
 * FLEXIBLE field declarations, derived from the migrations that own them.
 *
 * A SCHEMAFULL table rejects every sub-field the schema does not name unless
 * the field is FLEXIBLE. Tenants whose data crossed the 2.3.10 → 3.1.5 cut
 * hold stored definitions WITHOUT the flag while the migration ledger says
 * the defining migration ran, and `IF NOT EXISTS` never reconciles an
 * existing definition.
 *
 * The mechanism is the exporter, not our DDL (reproduced 2026-09-09 with
 * 2.3.10 → 2.6.5 in-place → `surreal export --v3` → 3.1.5 import): the
 * 2.6.5 `--v3` writer emits `TYPE option<object>` and `TYPE
 * option<array<object>>` with the FLEXIBLE keyword dropped, and keeps it
 * only on a plain `TYPE object`. So the drifted set on the server is
 * exactly "every `option<object> FLEXIBLE` field whose defining migration
 * ran before the cut" — 14 fields in `system` (declared up to 0057), 6 in
 * the registered tenant (declared up to 0035) — and every plain `object
 * FLEXIBLE` field, and every `option<object>` declared on 3.x afterwards,
 * is intact. 0134 repaired the four `job_run` fields of that set.
 *
 * Repairing the rest by retyping ~45 declarations by hand is how 0134's
 * first attempt got several wrong; this module reads each field's LATEST
 * declaration out of the migration files instead, so the generated
 * reconcile migration cannot disagree with the schema it restates. Every
 * declaration is listed, not only the drifted ones: OVERWRITE on a
 * correct field is a no-op, and the list must not depend on which servers
 * were inspected.
 */

export interface FlexibleFieldDeclaration {
  table: string;
  field: string;
  /** The migration file holding the latest declaration of this field. */
  migration: string;
  /** `DEFINE FIELD OVERWRITE <field> ON <table> <clauses>` — no trailing `;`. */
  statement: string;
}

const MIGRATION_FILE = /^(\d{4})_.+\.surql$/;
/** The generated reconcile file must never be its own source. */
const RECONCILE_FILE = /_flexible_reconcile\.surql$/;

const DEFINE_FIELD =
  /^DEFINE\s+FIELD\s+(?:IF\s+NOT\s+EXISTS\s+|OVERWRITE\s+)?(\S+)\s+ON\s+(?:TABLE\s+)?(\S+)\s+([\s\S]*)$/i;

/** Strip `-- …` line comments, then split on `;`. Good enough for DDL files. */
export function statementsOf(sql: string): string[] {
  const noComments = sql
    .split('\n')
    .map((line) => line.replace(/--.*$/, ''))
    .join('\n');
  return noComments
    .split(';')
    .map((s) => s.trim())
    .filter((s) => s.length > 0);
}

/**
 * Every (table, field) whose LATEST `DEFINE FIELD` across the migrations
 * carries FLEXIBLE, sorted by table then field. A field re-defined later
 * without the flag is deliberately absent — the schema dropped it.
 */
export function collectFlexibleFields(migrationsDir: string): FlexibleFieldDeclaration[] {
  const files = readdirSync(migrationsDir)
    .filter((f) => MIGRATION_FILE.test(f) && !RECONCILE_FILE.test(f))
    .sort();
  const latest = new Map<
    string,
    { table: string; field: string; migration: string; tail: string }
  >();
  for (const name of files) {
    const sql = readFileSync(join(migrationsDir, name), 'utf8');
    for (const statement of statementsOf(sql)) {
      const m = DEFINE_FIELD.exec(statement);
      if (!m) continue;
      const [, field, table, tail] = m as unknown as [string, string, string, string];
      latest.set(`${table}::${field}`, { table, field, migration: name, tail: tail.trim() });
    }
  }
  return [...latest.values()]
    .filter((d) => /\bFLEXIBLE\b/i.test(d.tail))
    .sort((a, b) => a.table.localeCompare(b.table) || a.field.localeCompare(b.field))
    .map((d) => ({
      table: d.table,
      field: d.field,
      migration: d.migration,
      statement: `DEFINE FIELD OVERWRITE ${d.field} ON ${d.table} ${d.tail}`,
    }));
}

/** The reconcile migration, byte-for-byte. */
export function renderFlexibleReconcile(declarations: FlexibleFieldDeclaration[]): string {
  const header = `-- Re-assert FLEXIBLE on every field that declares it.
--
-- GENERATED by \`pnpm migrations:flexible\` from the migrations before it
-- (src/db/flexible-fields.ts); test/flexible-reconcile.unit-spec.ts fails
-- when this file and the declarations disagree. Do not edit by hand.
--
-- Why: the 2.3.10 -> 3.1.5 cut (2026-07-15) moved every database through
-- \`surreal export --v3\` on 2.6.5, and that writer drops the FLEXIBLE
-- keyword from \`option<object>\` / \`option<array<object>>\` declarations
-- while keeping it on a plain \`object\` (reproduced 2026-09-09). A tenant
-- that crossed the cut therefore holds \`TYPE none | object\` WITHOUT
-- FLEXIBLE for every such field whose defining migration ran before the
-- cut, while the ledger says the migration ran, and IF NOT EXISTS never
-- reconciles an existing definition. A SCHEMAFULL table then rejects every
-- sub-field the schema does not name ("Found field 'error.message', but no
-- such field exists"). Measured on the server: 14 drifted fields in
-- \`system\` (declared up to 0057), 6 in the registered tenant (declared up
-- to 0035); every plain-object field and every option<object> declared on
-- 3.x is intact. 0134 repaired the four job_run fields of that set after
-- fn::reap_zombies had failed on every sweep; this covers the whole class,
-- each field with its LATEST declaration verbatim. OVERWRITE restates type,
-- optionality, default and permissions and touches no rows, so on a correct
-- field it is a no-op — which is why every declaration is listed, not only
-- the ones a particular server was seen to have lost.
`;
  const body = declarations.map((d) => `-- ${d.migration}\n${d.statement};`).join('\n');
  return `${header}\n${body}\n`;
}
