// Auto-generated by scripts/build-skill-versions.ts — do not edit.
export const skillChangelog = `# Skills Changelog

All notable changes to the bundled \`skills/\` directory.

The bundle ships as a single versioned unit (semver in \`skills/VERSION\`).
No per-skill versions — bump-skill-versions patch-bumps the bundle when
any file under \`skills/<name>/**\` changes.

## [0.4.0] — 2026-09-02

Docs refresh to the current MCP surface. The bundle had drifted badly:
skills described a 21-tool surface (15 read / +5 write / +1 admin)
while the server now registers up to **30 built-in tools + 2
resources** — 19 read always (+ \`get_fact\`, \`get_fact_provenance\`
under \`FACTS_API_ENABLED\` = 21), 8 write under \`brain:write\` (incl.
\`ingest_document\` under \`DOCUMENT_INGEST_ENABLED\`), 1 admin — plus
pack-declared tools under \`MCP_PACK_TOOLS_ENABLED\`. Minor bundle bump
— no breaking changes.

### MCP tools now covered

- \`get_fact\` / \`get_fact_provenance\` — one fact's full trust record
  (incl. \`groundingStatus\`) and the verbatim grounding turns behind
  it; registered when the server runs \`FACTS_API_ENABLED\`. Read scope.
- \`graph_retrieve\` — graph-first retrieval around named entities
  (1-hop neighbourhood, predicateHints, soft-fail to empty). Read scope.
- \`why\` / \`recall_decisions\` — code-memory recall (one anchor /
  semantic search). Read scope.
- \`get_source_reputation\` — learned trust profile of a source
  vertical. Read scope.
- \`ingest_document\` — Source → Indexer → Candidates → Brain pipeline
  for multi-claim prose, incl. the \`toolObservationRef\` provenance hop
  (\`TOOL_OBSERVATIONS_ENABLED\`). Write scope.
- \`record_feedback\` — helpful / not_helpful / incorrect per fact, one
  standing vote per caller key. Write scope.
- \`record_decision\` — code-memory write. Write scope.

### Skill updates

- \`brain-mcp-setup\` — scope matrix rewritten to the real surface
  (19/21 read → up to 29 with write → up to 30 with admin; the old
  matrix said 15/20/21 and the description claimed "all 14 brain
  tools"); \`brain:read_media\` row added (env-key-only media evidence
  scope); resources + pack-tools noted.
- \`brain-write\` — \`record_fact\` examples now show the
  \`conversationId\` + \`evidence[]\` grounding inputs and explain the
  claim-grounding plane (\`groundingStatus\`); new \`ingest_document\`
  (with \`toolObservationRef\`) and \`record_feedback\` sections.
- \`brain-search\` — \`graph_retrieve\` routing rule; \`limit\` bound fixed
  (1..100); companion list picks up the fact-read, source-reputation
  and code-memory tools.
- \`brain-recall\` — \`styleHint: 'client_llm'\` (MCP sampling) documented;
  \`get_fact\` / \`get_fact_provenance\` as the "why do you remember this"
  companions.
- \`brain-conflict\` — \`get_source_reputation\` for adjudication and the
  detect_contradiction fidelity note; fact-read companions.

## [0.3.0] — 2026-06-23

Read surface picked up four more MCP tools and two new workflow
skills; existing skills updated to point at them. Minor bundle bump
— no breaking changes.

### MCP tools (now live in \`src/mcp/mcp.service.ts\`)

- \`memory_diff\` — "what changed between two ISO 8601 cursors"
  surface. Returns createdFacts / retractedFacts / changedFacts (with
  before+after) / newEntities / forgottenEntities for \`[from, to)\`.
  Killer use case: session-resume agents fetch
  \`memory_diff(lastSessionEnd, now)\` and brief the user on what brain
  learned while they were away. Read scope.
- \`get_competing_facts\` — list facts in COMPETING status for an
  entity, grouped by predicate. 2-fact groups are resolver-left
  pairs; 3+ groups are multi-way conflicts escalated for human
  review. Drives in-product reviewer queues. Read scope.
- \`detect_contradiction\` — read-only dry-run of \`fn::resolve_fact\`.
  Predicts INSERTED / SUPERSEDED / COMPETING / REJECTED for a
  candidate fact without writing. Use as preflight before
  \`record_fact\` when contested writes are expensive. Read scope.
- \`summarize_entity\` — one-line briefing about an entity
  (name + top facts + refs), in-process LRU-cached. Saves three
  round-trips vs \`get_entity_profile\` + \`get_entity_timeline\` +
  \`get_competing_facts\` when all the agent needs is a single line of
  context. Three styleHint registers (\`neutral\` / \`sales\` /
  \`support\`); v1 is template-rendered, LLM-backed generator behind a
  feature flag is the next step. Read scope.

### Skill updates

- \`brain-recall\` — adds \`summarize_entity\` as the one-line briefing
  short-circuit + \`get_competing_facts\` for unresolved disagreements.
  Question/tool matrix expanded to five columns.
- \`brain-bitemporal\` — new section on \`memory_diff\` as the canonical
  "what changed since X" surface; mentions \`asOf\` on
  \`search_multi_hop\`; new "when did we first learn this" subsection.
- \`brain-search\` — companion-tool list updated.
- \`brain-mcp-setup\` — Aider / Goose v2 / Continue.dev / raw
  \`@modelcontextprotocol/sdk\` client configs added; scope matrix
  expanded to the full 14-tool surface.

### New skills

- \`brain-write\` — record_fact / link_entities / retract_fact with
  confidence picking, identity_of cycle guards, and the retract-vs-
  forget decision. Pairs \`detect_contradiction\` as preflight.
- \`brain-conflict\` — COMPETING fact status, get_competing_facts,
  detect_contradiction preflight, and the human-in-the-loop
  adjudication workflow. Covers 2-fact pairs vs 3+ multi-way
  conflicts and the dreams resolver's auto-resolution path.

## [0.2.0] — 2026-06-23

MCP surface picked up four new tools — skills point at them. Minor
update across \`brain-search\`; no breaking changes to existing skill
behaviour.

### MCP tools (now live in \`src/mcp/mcp.service.ts\`)

- \`search_multi_hop\` — planner-LLM-driven chained search with the
  running entity set anchored across hops. Use for questions that
  combine evidence across turns / sessions ("tenants who complained
  in April AND upgraded after"). Read scope.
- \`synthesize\` — corrective-RAG with the strict / lenient / off
  guardrail trio + claim-level faithfulness verifier. Read scope.
- \`link_entities\` — declare a typed edge between two entities. The
  \`identity_of\` kind merges two records of the same person across
  verticals; other kinds (\`paid_for\`, \`mentioned_in\`, …) participate
  in PPR / SubgraphRAG context. Write scope.
- \`forget_entity\` — GDPR-grade hard cascade with an HMAC tombstone.
  Reason enum is locked (\`gdpr_request\` / \`tenant_offboarding\` /
  \`operator_request\`); requestId is required for the audit trail.
  Admin scope.

### Skill updates

- \`brain-search\` — calls out when to escalate to \`search_multi_hop\`
  vs \`synthesize\` vs the one-shot \`search_knowledge\`; companion-
  tool list now includes the four new tools.

## [0.1.0] — 2026-05-22

Initial brain skills bundle.

### New skills

- \`brain-search\` — semantic + bitemporal search workflow for AI agents
- \`brain-recall\` — entity profile + timeline + connections workflow
- \`brain-bitemporal\` — formulating \`asOf\` queries and reading retracted facts
- \`brain-mcp-setup\` — connect a new MCP client to brain (Claude Desktop / Cursor / Goose)
`;
